mace_run_train \
    --name="MACE" \
    --foundation_model="mace-mpa-0-medium.model" \
    --multiheads_finetuning=True \
    --train_file="train.xyz" \
    --valid_fraction=0.05 \
    --test_file="test.xyz" \
    --energy_weight=1.0 \
    --forces_weight=1.0 \
    --E0s="{"1": 130.0 }" \
    --lr=0.01 \
    --scaling="rms_forces_scaling" \
    --batch_size=2 \
    --max_num_epochs=6 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --pt_train_file="mp" \
    --default_dtype="float64" \
    --device=cuda \
    --seed=3
